### ISSUE TITLE
Nothing happens when booting up a game

### ISSUE THREAD

**Issue by Madgenta** [PabloMK7/ArticBaseServer#26] opened 2024-06-22 23:02 UTC
Hello, I have installed Artic Base and followed the instructions.
It seems nothing happens after starting the server, it redirects me to the home screen after telling me to start any game, however no matter which game I pick, it simply boots normally without anything happening, the game remains playable and booting up Artic Base again repeats the welcome message and instructions.

Am I missing a step ? Or is something wrong with my firmware ?
Thanks in advance.

**Comment by PabloMK7** [comment] 2024-06-22 23:11
Hello. Make sure you are using the latest official Luma3DS version. Make sure there is a luma folder in your SD and there is a plugins folder inside it. Make sure your SD is not lock protected or corrupted, you can copy everything to a PC and format the SD to make sure. Make sure you are not trying to launch homebrew applications or GBA/DS games. 

I'll close this as it's not a bug in the app.

**Closed by PabloMK7** 2024-06-22 23:11 UTC

**Comment by Madgenta** [comment] 2024-06-22 23:25
Hello again, I have done everything already, I'm on Luma 13.1.2, there's a luma folder and a plugin folder inside it, my SD card is fine. I am not trying to boot a homebrew app or a GBA/DS game, it's a classic 3ds game.

If this isn't the appropriate place for this issue, where else can I ask for support regarding my problem ? Is there a discord server with a support channel I could join ?

**Comment by PabloMK7** [comment] 2024-06-22 23:32
Make sure you are using the latest artic base version, 1.0.1

**Comment by Madgenta** [comment] 2024-06-22 23:56
I am using the latest version
