### ISSUE TITLE
Fatal Error - Fire Emblem Awakening

### ISSUE THREAD

**Issue by cloud1nterval** [PabloMK7/ArticBaseServer#6] opened 2024-05-13 22:47 UTC
Hi, thank you so much for the tool! I have tried with with a few games that work perfectly (Pokémon Y, Fantasy Life), but for some reason I get a Fatal Error from Citra with Fire Emblem Awakening, and I can't boot up the game 

[citra_log copy.txt](https://github.com/PabloMK7/ArticBaseServer/files/15300678/citra_log.copy.txt)
![Screenshot 2024-05-13 at 5 36 44 PM](https://github.com/PabloMK7/ArticBaseServer/assets/104915830/a9f74648-f943-498b-a632-bf287b1a697d)

**Comment by PabloMK7** [comment] 2024-05-21 06:47
Is this bug still present after the newest updates to citra and artic base?

**Comment by cloud1nterval** [comment] 2024-05-22 22:47
Hey Pablo, 

I installed v. 1.0.1 and got the same error
[citra_log.txt](https://github.com/PabloMK7/ArticBaseServer/files/15409349/citra_log.txt)

**Comment by PabloMK7** [comment] 2024-07-07 13:30
I'm using the latest citra build and latest Artic Base. I cannot reproduce the issue. The game loads and plays without problems. I will need more context to be able to fix this. Do you have the dlc? Do you have a save file you could share?

**Comment by PabloMK7** [comment] 2024-07-09 19:51
Looking at the result code from the log, this was probably fixed by: https://github.com/PabloMK7/citra/pull/171

**Closed by PabloMK7** 2024-07-09 19:51 UTC
