### ISSUE TITLE
"Error reading from socket"/Citra also crashing (was told to throw this onto the github issue page) (also never used an issue page before so hopefully I did this right)

### ISSUE THREAD

**Issue by CursiveTheFont** [PabloMK7/ArticBaseServer#1] opened 2024-05-12 20:37 UTC
[citra_log.txt](https://github.com/PabloMK7/ArticBaseServer/files/15287598/citra_log.txt)

**Comment by QuentinWehkamp** [comment] 2024-05-12 20:53
I'm having the exact same issue
[citra_log.txt.old.txt](https://github.com/PabloMK7/ArticBaseServer/files/15287636/citra_log.txt.old.txt)

**Comment by babtown** [comment] 2024-05-12 21:13
I have the same issue, here is footage of what happened on the pc and 3ds in real time as well as the citra log

https://github.com/PabloMK7/ArticBaseServer/assets/30322271/c107c6cd-31c7-43ca-93a3-195ffcc917be

[citra_log.txt](https://github.com/PabloMK7/ArticBaseServer/files/15287666/citra_log.txt)

**Comment by DetectiveMecha** [comment] 2024-05-12 21:35
Also having this problem, exact same error process as the video above
[citra_log.txt.old.txt](https://github.com/PabloMK7/ArticBaseServer/files/15287704/citra_log.txt.old.txt)

**Comment by nabekos** [comment] 2024-05-12 23:59
same issue
[citra_log.txt.old.txt](https://github.com/PabloMK7/ArticBaseServer/files/15288003/citra_log.txt.old.txt)

**Comment by Dal1ster** [comment] 2024-05-13 01:11
[citra_log.txt](https://github.com/PabloMK7/ArticBaseServer/files/15288279/citra_log.txt)
yeah, i managed to run tomodachi life the first time i used arctic base, but every time after it causes citra to throw and error and for it to get stuck at the 3 objects loading screen

**Comment by jinjimeow** [comment] 2024-05-13 01:34
same issue

**Comment by fignewtonss** [comment] 2024-05-13 01:43
same issue

**Comment by Fenixien** [comment] 2024-05-13 07:42
Same issues as users above.

**Comment by PabloMK7** [comment] 2024-05-13 09:03
Duplicate of https://github.com/PabloMK7/citra/issues/110

**Closed by PabloMK7** 2024-05-13 09:03 UTC
