### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Timothy14f** [PabloMK7/ArticBaseServer#31] opened 2024-07-21 16:04 UTC
The connection keeps failing. Both devices are on the same network. I am using Citra (Android).
![photo](https://github.com/user-attachments/assets/9946b459-5b65-482e-86c0-b0389d890fcc)
![Screenshot_20240721_173253_Citra](https://github.com/user-attachments/assets/ef08136f-d38e-46af-9edf-5cbea155a48b)

**Comment by PabloMK7** [comment] 2024-07-21 20:25
Update citra to the latest verison and try again.

**Comment by Timothy14f** [comment] 2024-07-24 18:49
Still not working.

**Comment by PabloMK7** [comment] 2024-07-24 19:18
Please send the citra log.

**Comment by Timothy14f** [comment] 2024-07-24 19:23
[citra_log.txt.old.txt](https://github.com/user-attachments/files/16366675/citra_log.txt.old.txt)

**Comment by PabloMK7** [comment] 2024-07-24 19:28
The log only mentions a generic communication error. There might be network issues with your console or phone.

**Comment by Timothy14f** [comment] 2024-07-24 19:30
I have no visible network problems at all.

**Comment by Timothy14f** [comment] 2024-07-27 01:14
So you have no plan? Me neither.

**Comment by PabloMK7** [comment] 2024-09-01 10:27
This is caused by some misconfiguration in your network. Closing as it's not an artic base bug.

**Closed by PabloMK7** 2024-09-01 10:27 UTC
